### ISSUE TITLE
Database Environment [How]

### ISSUE THREAD

**Issue by Dokman** [animecenter/animecenter#36]
How we use the database environment... cause in all sql statements are getted from a server but there is no response...

**Comment by christianpv** [comment]
Please follow https://github.com/animecenter/animecenter#setup, and let me know if you find any problem. It should set up a dummy database for you.

**Comment by Dokman** [comment]
i used the setup... but.. all is not showing correctly...

**Comment by christianpv** [comment]
Can you post a screenshot and/or post the error you are getting? Did you follow all steps? I just updated it today, and tried it on a new computer which is working correctly. Make sure to pull the latest changes with `git pull --recurse-submodules`.
